image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_TLS_CERTDIR: ""

.install:
  before_script:
    - cd reddit
    - bundle install

.docker:
  image: docker:20.10.11
  services:
    - docker:dind
  before_script:
    - docker login --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASS

build_job:
  extends: .docker
  stage: build
  script:
    - echo 'Building'
    - docker build -t $DOCKER_USER/reddit:${CI_COMMIT_TAG} .
    - docker push $DOCKER_USER/reddit:${CI_COMMIT_TAG}

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

test_unit_job:
  extends: .install
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

branch review:
  stage: review
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker run -d -p 9292:9292 $DOCKER_USER/reddit:${CI_COMMIT_TAG}
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com


production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
