---
- name: Create runner container
  community.docker.docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: yes
    state: started
    privileged: yes
    volumes:
      - /srv/gitlabrunner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

- name: set gitlab_runner_token
  set_fact:
    gitlab_runner_token: "{{ runner_registration_token.stdout }}"

- name: register docker runner
  command: |
    docker exec -it gitlab-runner gitlab-runner register \
    --url http://{{ ansible_host }} \
    --non-interactive \
    --locked=false \
    --name DockerRunner \
    --registration-token {{ gitlab_runner_token }} \
    --executor docker \
    --docker-image alpine:latest \
    --docker-privileged \
    --tag-list "linux,xenial,ubuntu,docker" \
    --run-untagged
