---
- name: Install Docker
  hosts: all
  become: true
  tasks:

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install

    - name: Add repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://download.docker.com/linux/ubuntu bionic stable
        update_cache: yes
        state: present
      tags: install

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      tags: install

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: service docker
      service:
        name: docker
        state: started
        enabled: yes
