version: '3.3'
services:
  post_db:
    container_name: "${COMPOSE_PROJECT_NAME}_mongo"
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - comment_db
          - mongo_db

  ui:
    container_name: "${COMPOSE_PROJECT_NAME}_ui"
    image: ${USER_NAME}/ui:${VER_UI}
    ports:
      - ${PORT_UI}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - frontend
  post:
    container_name: "${COMPOSE_PROJECT_NAME}_post"
    image: ${USER_NAME}/post:${VER_POST}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - backend
      - frontend
  comment:
    container_name: "${COMPOSE_PROJECT_NAME}_comment"
    image: ${USER_NAME}/comment:${VER_COMMENT}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - backend
      - frontend


volumes:
  post_db:
  prometheus_data:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.8.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.7.0/24
