- name: gitlab container
  community.docker.docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    env:
        GITLAB_OMNIBUS_CONFIG: external_url 'http://{{ groups['gitlab'] }}'
