- name: Create runner container
  community.docker.docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: yes
    state: started
    volumes:
      - /srv/gitlabrunner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
