---
# file: k8s-worker.yml

- hosts: master
  become: true
  tasks:

    - name: get worker registration token
      shell: kubeadm token create --print-join-command
      register: kuber_registration_token

    - name: Set worker join command
      set_fact:
        worker_join_command: "{{ kuber_registration_token.stdout }}"


- hosts: worker
  become: true
  tasks:

    - name: join cluster
      shell: |
        {{ hostvars[groups['master'][0]]['worker_join_command'] }}
