version: '3.3'
services:
  post_db:
    container_name: "${COMPOSE_PROJECT_NAME}_mongo"
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    container_name: "${COMPOSE_PROJECT_NAME}_ui"
    build: ./ui
    image: ${MY_USERNAME}/ui:${VER_UI}
    ports:
      - ${PORT_UI}:9292/tcp
    networks:
      - frontend
  post:
    container_name: "${COMPOSE_PROJECT_NAME}_post"
    build: ./post-py
    image: ${MY_USERNAME}/post:${VER_POST}
    networks:
      - backend
      - frontend
  comment:
    container_name: "${COMPOSE_PROJECT_NAME}_comment"
    build: ./comment
    image: ${MY_USERNAME}/comment:${VER_COMMENT}
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.8.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.7.0/24
